### ISSUE TITLE
Bug: item drag preview effected by canvas layer position.

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#238] opened 2024-09-08 11:58 UTC
Help! :pray:  

If I have my ctrl_inventory_grid_ex control not at position 0,0 I get the following behaviour of drag preview not working in the whole grid: https://github.com/user-attachments/assets/b99e61a9-0969-4fc2-894d-16f0225a6898

The drag preview is working in the whole grid only if I position it at the origin of the canvas layer Vector2(0,0) (or perhaps the root node of the scenes position). This is evident because If I set the canvas_layer with an offset whilst keeping the ctrl_inventory_grid_ex position at 0,0 it still works. (therefore my player inventory drag preview in bottom right not work at all).

My node hierachy; I have it nested in a canvas layer so it doesn't rotate with my player); In this screenshot the inventory works because I offset the canvas layers transform, but if I kept it at 0,0 and moved the ctrl_inventory_grid_ex instead you end up with behaviour in video...
![image](https://github.com/user-attachments/assets/f64c1312-7fa3-41ad-b83e-b542f89337bb)

So, I guess it needs to calculate drag preview from the controls position rather than whatever its calculating from? , Or maybe its more complicated :shrug:

**Comment by LeeWannacott** [comment] 2024-09-08 14:40
Update: Commenting out this line fixes this issue for me. Is this actually doing anything because it seems to reset to field style when not hovering anyway?
https://github.com/peter-kish/gloot/blob/d05decba6495e4f6da498689545e34e127160022/addons/gloot/ui/ctrl_inventory_grid_ex.gd#L368-L370

**Comment by peter-kish** [comment] 2024-09-13 20:13
I was able to reproduce this partially. I see an issue with the missing background highlights, but the drag preview seems to work fine:
![Peek 2024-09-13 22-08](https://github.com/user-attachments/assets/8a0faae9-f6f2-4c26-9861-494e0c1337d5)
The missing highlights should be fixed in 7c69809030907703279fc21e6ffba4c60b000f91. You can give it a try, maybe it fixes your issue. If not, I'll keep investigating.

**Comment by LeeWannacott** [comment] 2024-09-14 06:29
> The missing highlights should be fixed in https://github.com/peter-kish/gloot/commit/7c69809030907703279fc21e6ffba4c60b000f91. You can give it a try, maybe it fixes your issue. If not, I'll keep investigating.

Yep, that fixed it! nice one!. 

What do you think of adding an option for field highlighted style? say for two colors, one for if the item is swappable (green by default) and one for if its not swappable (red by default) and/or making the cursor a cross if the item isn't swappable? because it can be confusing when part of your item is transparent...

**Comment by peter-kish** [comment] 2024-09-14 08:29
> What do you think of adding an option for field highlighted style?

At some point yeah, why not. It's just that that I'm not sure if I will squeeze it in v2. Mostly because I'm trying to only do bugfixes and maintenance on v2, while I implement the new features in v3.

I created a [separate issue](https://github.com/peter-kish/gloot/issues/247) for this without any milestones set. If it turns out to be simple enough, I'll include it in v2.

**Comment by LeeWannacott** [comment] 2024-09-14 08:33
> At some point yeah, why not. It's just that that I'm not sure if I will squeeze it in v2. Mostly because I'm trying to only do bugfixes and maintenance on v2, while I implement the new features in v3.

Cool, I'm going to try porting to v3 anyway; I just ported my protoset to json using macros. Hopefully its not too painful...

**Closed** 2024-09-14 08:42 UTC
Labels: bug
