### ISSUE TITLE
Godot 4 branch is incompatible with the latest beta version (Beta 16)

### ISSUE THREAD

**Issue by scriptsengineer** [peter-kish/gloot#80] opened 2023-01-28 22:58 UTC
```
res://tests/item_definitions_test.gd:3 - Parse Error: "Inventory" was not found in the current scope
Line 3:Annotation "@tool" must be at the top of the script, before "extends" and "class_name".
```
This happens with all scripts that contain @tool

**Comment by peter-kish** [comment] 2023-01-29 11:11
Yeah, I just noticed. The Godot 4 branch is still not quite stable, and development was done using Godot Beta 10, where the issue is not present.
I'll have to update it to the latest beta and fix all potential errors.

Thanks for the heads-up!

**Comment by peter-kish** [comment] 2023-02-15 08:38
A small update on this:
I switched to Godot 4.0 RC2 and fixed some of the above mentioned issues, but I unfortunately ran into an [issue](https://github.com/godotengine/godot/issues/72963) with RC2 that is yet to be fixed. There's a [PR open](https://github.com/godotengine/godot/pull/72984) since a few days ago, but I'm not sure if it will make it into the next Godot 4 version or when.

**Comment by peter-kish** [comment] 2023-02-22 20:01
Should be fixed in https://github.com/peter-kish/gloot/commit/f39547be84ec20131571f41a167f42eac0eb5218.
The [issue](https://github.com/godotengine/godot/issues/72963) from RC2 has been fixed in [RC3](https://godotengine.org/article/release-candidate-godot-4-0-rc-3/).

**Closed by peter-kish** 2023-02-22 20:01 UTC
Labels: bug
