### ISSUE TITLE
Changing inventory_grid for CtrlInventoryGridEx doesn't increase size of custom textures.

### ISSUE THREAD

**Issue by emilyallerdings** [peter-kish/gloot#143] opened 2024-01-12 05:37 UTC
![Example Video](https://github.com/peter-kish/gloot/assets/17506903/99fce656-6955-4b11-b135-41887f4d3a83)

When I try to set the inventory just by using:

ctrl_inventory_grid_ex.inventory = inventory_grid

I get this issue when switching to inventories with a larger size than the previous. Is there a way to fix this?

**Comment by emilyallerdings** [comment] 2024-01-12 05:42
Manually calling _refresh_field_background_grid() on the CtrlInventoryGridEx seems to fix it, but this doesn't seem like a proper solution.

**Comment by peter-kish** [comment] 2024-01-13 11:21
Hmm... I tried to create an identical scene with the latest version, but couldn't reproduce the issue:
![Peek 2024-01-13 12-18](https://github.com/peter-kish/gloot/assets/11254996/b78b07fe-5f28-484b-80ee-e11ac23bba44)

Can you provide a Godot project or scene so I can take a closer look?

**Comment by emilyallerdings** [comment] 2024-01-16 02:18
Is that with a custom field style? That's the part that doesn't seem to scale when changing inventories.

Here's my example project of the problem happening. https://github.com/emilyallerdings/Gloot-Test/

**Comment by peter-kish** [comment] 2024-01-19 15:44
This took me quite some time to fix because I somehow completely misunderstood the issue 🙃.
Anyways, you were right, a `_refresh_field_background_grid` was missing somewhere. It should be fixed now (250766c3ccff4e3b3084ddaf233b221982ed85f6).

**Closed** 2024-01-21 10:18 UTC
