### ISSUE TITLE
Long execution of transfer()

### ISSUE THREAD

**Issue by juliusspeak** [peter-kish/gloot#164] opened 2024-02-20 05:39 UTC
Is there a way to make the transfer function work faster? At some point, the game even freezes.
Transferring 32 items took 5.67 seconds, and at that moment, the game doesn't allow any actions.
![img](https://github.com/peter-kish/gloot/assets/35423496/f4ff87ba-0c03-4e9c-b405-2bd6a92f7a88)

i use this code:
```gdscript
	var itemsToTransfer = cartInventory.get_items()
	for i in itemsToTransfer.size():
		if inventory.can_add_item(itemsToTransfer[0]):
			cartInventory.transfer(itemsToTransfer[0], inventory)
		else:
			cartPrice -= itemsToTransfer[0].get_property("buyPrice")
```

**Comment by peter-kish** [comment] 2024-02-20 16:57
Ugh, that doesn't look good. Not the first time that `InventoryGrid` needs optimization...

**Comment by peter-kish** [comment] 2024-02-20 17:05
Btw, your game looks great! 🍺

**Comment by juliusspeak** [comment] 2024-02-20 17:08
Thank you very much! I have many plans, so with gloot, I'll be around for a long time, which means I'll create a lot of themes as well.

**Comment by peter-kish** [comment] 2024-02-20 20:37
Cool, I hope it will meet your needs 🙂

So, I suppose you were using `InventoryGrid`... I threw together this test which transfers 32 1x1 items from one 6x6 inventory to another:
```gdscript
func test_transfer_performance():
    var i1 = create_inventory_grid(TEST_PROTOSET, Vector2i(6, 6))
    var i2 = create_inventory_grid(TEST_PROTOSET, Vector2i(6, 6))
    const ITEM_COUNT = 32
    for i in ITEM_COUNT:
        assert(i1.create_and_add_item("item_1x1") != null)

    var start_time := Time.get_ticks_msec()
    while i1.get_item_count() > 0:
        var item := i1.get_items()[0]
        if i2.can_add_item(item):
            i1.transfer(item, i2)
    var end_time := Time.get_ticks_msec()
    print("Elapsed time: %d" % (end_time - start_time))

    free_inventory(i1)
    free_inventory(i2)
```
and it seems to execute in only 4ms:
```
Running InventoryGridTests:test_transfer_performance
Elapsed time: 4
```
Then I modified it to use 2x2 items and 12x12 inventories and that one executed somewhat slower, but nowhere near 5 seconds:
```
Running InventoryGridTests:test_transfer_performance
Elapsed time: 20
```

Can you tell me what item and inventory sizes you were using?
Also, can you try measuring the time before and after your `for` loop, similar to how I did? Just to make sure nothing else affected the performance.

**Comment by juliusspeak** [comment] 2024-02-21 08:42
```gdscript
func buyCart():
	var itemsToTransfer = cartInventory.get_items()
	var start_time := Time.get_ticks_msec()
	for i in itemsToTransfer.size():
		if inventory.can_add_item(itemsToTransfer[0]):
			cartInventory.transfer(itemsToTransfer[0], inventory)
		else:
			cartPrice -= itemsToTransfer[0].get_property("buyPrice")
	var end_time := Time.get_ticks_msec()
	print("Elapsed time: %d" % (end_time - start_time))
	MainScene.subMoney(cartPrice)
	changeCartPrice()
```
Elapsed time: **15678**

**Comment by peter-kish** [comment] 2024-02-21 19:47
Ok I managed to reproduce the issue and it looks like the problem is inside `CtrlInventoryGrid` - it is being re-assembled every time an item is added, which is really unnecessary.
Seems like I have a lot of optimization work to do...

**Comment by peter-kish** [comment] 2024-02-21 20:22
I implemented some basic performance improvements that I should have done long time ago. It's still not perfect, but it should improve performance significantly.
I pushed the changes to the [dev_v2.4.3](https://github.com/peter-kish/gloot/tree/dev_v2.4.3) branch and I'll merge them to master if no additional problems come up.

**Comment by peter-kish** [comment] 2024-02-24 12:24
Merged.

**Closed by peter-kish** 2024-02-24 12:24 UTC
Labels: bug
