### ISSUE TITLE
Bug: set_rect_backgound array out of bounds error.

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#193] opened 2024-04-15 17:27 UTC
Its called by _highlight_grabbed_item.

https://github.com/peter-kish/gloot/assets/49783296/c257b465-9628-480b-a8e1-278948c3efdd

![image](https://github.com/peter-kish/gloot/assets/49783296/83a43397-7edf-4c00-87d3-f16f60d2c4db)

**Comment by peter-kish** [comment] 2024-04-15 18:16
Ugh, those negative rect coordinates don't look good...

A few questions:
1. So, this randomly happens while dragging an item across the screen? Or does it happen on a drop?
2. How often does it happen?
3. Did you start noticing this after the last release?

**Comment by LeeWannacott** [comment] 2024-04-15 18:27
> Ugh, those negative rect coordinates don't look good...
> 
> A few questions:
> 1. So, this randomly happens while dragging an item across the screen? Or does it happen on a drop?
> 2. How often does it happen?
> 3. Did you start noticing this after the last release?

1 when dragging, I'm not dropping; seems random. 3 I copied over from master to get your signals fix. 2 I can get it to happen quite easily. My guess the bugs always been there though. I'll investigate further tomorrow.

**Comment by peter-kish** [comment] 2024-04-17 16:16
I wasn't really able to reproduce this, but I made some assumptions on how it could happen and added some additional checks. The changes are on the [dev_v2.4.8](https://github.com/peter-kish/gloot/tree/dev_v2.4.8) branch. I'll do some more testing and eventually merge it to master. I hope it will fix the issue.

**Comment by LeeWannacott** [comment] 2024-04-17 18:29
> I wasn't really able to reproduce this, but I made some assumptions on how it could happen and added some additional checks. The changes are on the [dev_v2.4.8](https://github.com/peter-kish/gloot/tree/dev_v2.4.8) branch. I'll do some more testing and eventually merge it to master. I hope it will fix the issue.

Seems to fix the issue :tada: (before when I brought my item to about halfway on the screen it happened and doesn't now) , However there now seems to be a case of gigantasauras rex and  the icon is offcentre now from the mouse cursor...

https://github.com/peter-kish/gloot/assets/49783296/198cd002-f822-4d3e-95df-c82e0c7272a2

Also there is a separate issue from this that I have been meaning to report which is that items dragged from the inventory of my shop keepers the icon whilst dragging isn't centre its like off-screen; I think its caused by the shopkeepers being on a different canvas layer (I think they default to 0) than my players inventory (1), because I managed to fix it on one of them. I guess this is my problem to fix; it is a little bit annoying though...

**Comment by peter-kish** [comment] 2024-04-21 12:35
I played around with this a little, but couldn't reproduce the oversized drag icon problem. Can you give me some additional information about your scene (scaling, canvas layers etc.)?

As for the canvas layer problem, it seems to be a known Godot issue: https://github.com/godotengine/godot-docs/issues/4086
The issue is related to the camera position, but the same seems to happen if you have a canvas layer that is transformed in some way (non-zero offset and/or scale that is different from (1,1)). There are workarounds for this but they don't look very elegant ☹️.  But since the issue is open since 2020, I don't expect it to be fixed anytime soon, so I might implement one of these workarounds after all. Until then the only solution is to keep the canvas layer offset and scale at default.

**Comment by LeeWannacott** [comment] 2024-04-21 13:09
> I managed to reproduce the issue. Hope I'll come up with a fix soon.

Sweet, my project is getting complicated; it can be hard to figure out what is causing bugs.

> canvas layer that is transformed in some way (non-zero offset and/or scale that is different from (1,1))
I think my canvas layers are default, but they are in nested scenes, so they probably belong to different Viewports.

**Comment by peter-kish** [comment] 2024-05-01 07:24
Should be fixed in [v2.4.8](https://github.com/peter-kish/gloot/releases/tag/v2.4.8)

**Closed by peter-kish** 2024-05-01 07:24 UTC
Labels: bug
