### ISSUE TITLE
Clickthrough problem

### ISSUE THREAD

**Issue by LunaBold** [peter-kish/gloot#85] opened 2023-03-02 16:30 UTC
scroll boxes do not obey mouse input filter flags on parent control objects I.E. Stop, Pass, Ignore.

instead of having input blocked by the filter, you can click behind a control node and interact with a inventory behind it, the same goes for control nodes with clipped outside checked, for example a scrollbox will allow you to drag items not visible due to scrolling.

**Comment by peter-kish** [comment] 2023-03-02 20:31
I'm somewhat aware of this for a while now. I should probably use `_unhandled_input` instead of `_input` in a number of places to handle UI inputs.

**Comment by peter-kish** [comment] 2023-03-25 12:18
This has been partially fixed in 0ad1e4e8d61d4dfadc8abbf9598fea4712e22d82
Items can no longer be grabbed "behind" other controls, but the issue is still present with item drops.

You were, right, it had nothing to do with `_unahandled_input` after all, but rather with mouse input filters and `_gui_input()`.
Item drops are still an issue because `_gui_input()` is only called for "mouse released" (`InputEventMouseButton.pressed==false`) events if the same control previously triggered the "mouse pressed" event (`InputEventMouseButton.pressed==true`). This makes dragging items from one `CtrlInventoryGrid` to another (almost) impossible to implement with `gui_input()` and forces me to use `_input()`, which still has the problem of being detected "behind" other controls.

**Comment by LunaBold** [comment] 2023-03-25 12:35
glad you found it because i was struggling to replicate it and then forgot, sorry about that!

**Comment by peter-kish** [comment] 2023-12-16 20:33
Should be fixed in [v2.3.8](https://github.com/peter-kish/gloot/releases/tag/v2.3.8)

**Closed by peter-kish** 2023-12-16 20:33 UTC
Labels: bug
